var ADDRESS = {
  PROVIDER: 'CAPSULE-JS-STORAGE',
  CACHE: 'CAPSULE-JS-CACHE',
  MAINTAINER: 'CAPSULE-BRIDGE-REACT-MAINTAINER',
  PORTER: 'CAPSULE-BRIDGE-REACT-PORTER',
  EVENT: 'CAPSULE-BRIDGE-REACT-EVENT',
}

module.exports = ADDRESS;